version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "80:80"
    env_file:
      - ./frontend/.env
    networks:
      - coachkush-net

networks:
  coachkush-net:
    driver: bridge
